# Generated by Django 4.2.16 on 2024-10-21 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_issuedbook_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 5, 16, 58, 58, 209069)),
        ),
    ]
